# Site settings
title: My Territory
blog_title: My Territory
header-img: img/home-bg.jpg
email: 
copyright_name: David Camilo Sanchez Mora
description: "Online Territory of David Camilo Sanchez Mora"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url:  #only used in disque comments for now
disqus_url:  # disque comments are broken if you send http:// along with url
github_username:  davidsanchez96
facebook_username: david.sanchezmora.39
stackoverflow_username:
twitter_username:  deividsanchez96
codepen_username: davidsanchez96
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
